organization: Central Institute of Mental Health
organization_url: "https://www.zi-mannheim.de/en.html"
group_photo: "/assets/images/group_photo_2025.jpg"
group_photo_alt: ""
group_photo_y: "10%"
contact:
  email: daniel.durstewitz@zi-mannheim.de
  address: Zentralinstitut für Seelische Gesundheit (ZI), J5 68159 Mannheim, Abteilung für theoretische Neurowissenschaften, Laboratory Building, 4th Floor, Room 4.18 / Room 4.02